# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.CharField(choices=[(1, 'Um'), (2, 'Duas'), (3, 'Tres'), (4, 'Quatro'), (5, 'Cinco')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('comentario', models.TextField()),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('editora', models.CharField(blank=True, max_length=200, null=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(null=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenhas', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro', to='resenha.Livro')),
            ],
            options={
                'ordering': ('criado',),
            },
        ),
        migrations.AddField(
            model_name='comentario',
            name='resenha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='resenha.Resenha'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resenha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resenha.Resenha'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
